version: '3'

services:
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    restart: always
    ports:
      - 1113:1113
      - 2113:2113
    volumes:
      - es-data:/var/lib/eventstore
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  es-data:
  pg-data: